# Generated by Django 5.2.16 on 2026-07-21 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price_vip', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_regular', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
