# Generated by Django 5.2.16 on 2026-07-21 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=50, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.session')),
            ],
        ),
    ]
